// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: internal/proto/oddsfeed.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Sport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Slug          string                 `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sport) Reset() {
	*x = Sport{}
	mi := &file_internal_proto_oddsfeed_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sport) ProtoMessage() {}

func (x *Sport) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_oddsfeed_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sport.ProtoReflect.Descriptor instead.
func (*Sport) Descriptor() ([]byte, []int) {
	return file_internal_proto_oddsfeed_proto_rawDescGZIP(), []int{0}
}

func (x *Sport) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Sport) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Sport) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

type League struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	SportId       string                 `protobuf:"bytes,3,opt,name=sport_id,json=sportId,proto3" json:"sport_id,omitempty"`
	Country       string                 `protobuf:"bytes,4,opt,name=country,proto3" json:"country,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *League) Reset() {
	*x = League{}
	mi := &file_internal_proto_oddsfeed_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *League) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*League) ProtoMessage() {}

func (x *League) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_oddsfeed_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use League.ProtoReflect.Descriptor instead.
func (*League) Descriptor() ([]byte, []int) {
	return file_internal_proto_oddsfeed_proto_rawDescGZIP(), []int{1}
}

func (x *League) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *League) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *League) GetSportId() string {
	if x != nil {
		return x.SportId
	}
	return ""
}

func (x *League) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

type Event struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	LeagueId        string                 `protobuf:"bytes,2,opt,name=league_id,json=leagueId,proto3" json:"league_id,omitempty"`
	SportId         string                 `protobuf:"bytes,3,opt,name=sport_id,json=sportId,proto3" json:"sport_id,omitempty"`
	HomeParticipant string                 `protobuf:"bytes,4,opt,name=home_participant,json=homeParticipant,proto3" json:"home_participant,omitempty"`
	AwayParticipant string                 `protobuf:"bytes,5,opt,name=away_participant,json=awayParticipant,proto3" json:"away_participant,omitempty"`
	StartsAt        string                 `protobuf:"bytes,6,opt,name=starts_at,json=startsAt,proto3" json:"starts_at,omitempty"`
	Status          string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	HomeScore       string                 `protobuf:"bytes,8,opt,name=home_score,json=homeScore,proto3" json:"home_score,omitempty"`
	AwayScore       string                 `protobuf:"bytes,9,opt,name=away_score,json=awayScore,proto3" json:"away_score,omitempty"`
	ScoreUpdatedAt  string                 `protobuf:"bytes,10,opt,name=score_updated_at,json=scoreUpdatedAt,proto3" json:"score_updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_internal_proto_oddsfeed_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_oddsfeed_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_internal_proto_oddsfeed_proto_rawDescGZIP(), []int{2}
}

func (x *Event) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Event) GetLeagueId() string {
	if x != nil {
		return x.LeagueId
	}
	return ""
}

func (x *Event) GetSportId() string {
	if x != nil {
		return x.SportId
	}
	return ""
}

func (x *Event) GetHomeParticipant() string {
	if x != nil {
		return x.HomeParticipant
	}
	return ""
}

func (x *Event) GetAwayParticipant() string {
	if x != nil {
		return x.AwayParticipant
	}
	return ""
}

func (x *Event) GetStartsAt() string {
	if x != nil {
		return x.StartsAt
	}
	return ""
}

func (x *Event) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Event) GetHomeScore() string {
	if x != nil {
		return x.HomeScore
	}
	return ""
}

func (x *Event) GetAwayScore() string {
	if x != nil {
		return x.AwayScore
	}
	return ""
}

func (x *Event) GetScoreUpdatedAt() string {
	if x != nil {
		return x.ScoreUpdatedAt
	}
	return ""
}

type Market struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	EventId       string                 `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Line          string                 `protobuf:"bytes,5,opt,name=line,proto3" json:"line,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Market) Reset() {
	*x = Market{}
	mi := &file_internal_proto_oddsfeed_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Market) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Market) ProtoMessage() {}

func (x *Market) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_oddsfeed_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Market.ProtoReflect.Descriptor instead.
func (*Market) Descriptor() ([]byte, []int) {
	return file_internal_proto_oddsfeed_proto_rawDescGZIP(), []int{3}
}

func (x *Market) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Market) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *Market) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Market) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Market) GetLine() string {
	if x != nil {
		return x.Line
	}
	return ""
}

func (x *Market) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type Outcome struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MarketId      string                 `protobuf:"bytes,2,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Odds          string                 `protobuf:"bytes,4,opt,name=odds,proto3" json:"odds,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Outcome) Reset() {
	*x = Outcome{}
	mi := &file_internal_proto_oddsfeed_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Outcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Outcome) ProtoMessage() {}

func (x *Outcome) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_oddsfeed_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Outcome.ProtoReflect.Descriptor instead.
func (*Outcome) Descriptor() ([]byte, []int) {
	return file_internal_proto_oddsfeed_proto_rawDescGZIP(), []int{4}
}

func (x *Outcome) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Outcome) GetMarketId() string {
	if x != nil {
		return x.MarketId
	}
	return ""
}

func (x *Outcome) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Outcome) GetOdds() string {
	if x != nil {
		return x.Odds
	}
	return ""
}

func (x *Outcome) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListSportsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSportsRequest) Reset() {
	*x = ListSportsRequest{}
	mi := &file_internal_proto_oddsfeed_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSportsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSportsRequest) ProtoMessage() {}

func (x *ListSportsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_oddsfeed_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSportsRequest.ProtoReflect.Descriptor instead.
func (*ListSportsRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_oddsfeed_proto_rawDescGZIP(), []int{5}
}

func (x *ListSportsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListSportsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListSportsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sports        []*Sport               `protobuf:"bytes,1,rep,name=sports,proto3" json:"sports,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSportsResponse) Reset() {
	*x = ListSportsResponse{}
	mi := &file_internal_proto_oddsfeed_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSportsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSportsResponse) ProtoMessage() {}

func (x *ListSportsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_oddsfeed_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSportsResponse.ProtoReflect.Descriptor instead.
func (*ListSportsResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_oddsfeed_proto_rawDescGZIP(), []int{6}
}

func (x *ListSportsResponse) GetSports() []*Sport {
	if x != nil {
		return x.Sports
	}
	return nil
}

type ListLeaguesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SportId       string                 `protobuf:"bytes,1,opt,name=sport_id,json=sportId,proto3" json:"sport_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLeaguesRequest) Reset() {
	*x = ListLeaguesRequest{}
	mi := &file_internal_proto_oddsfeed_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLeaguesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLeaguesRequest) ProtoMessage() {}

func (x *ListLeaguesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_oddsfeed_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLeaguesRequest.ProtoReflect.Descriptor instead.
func (*ListLeaguesRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_oddsfeed_proto_rawDescGZIP(), []int{7}
}

func (x *ListLeaguesRequest) GetSportId() string {
	if x != nil {
		return x.SportId
	}
	return ""
}

func (x *ListLeaguesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListLeaguesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListLeaguesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Leagues       []*League              `protobuf:"bytes,1,rep,name=leagues,proto3" json:"leagues,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLeaguesResponse) Reset() {
	*x = ListLeaguesResponse{}
	mi := &file_internal_proto_oddsfeed_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLeaguesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLeaguesResponse) ProtoMessage() {}

func (x *ListLeaguesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_oddsfeed_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLeaguesResponse.ProtoReflect.Descriptor instead.
func (*ListLeaguesResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_oddsfeed_proto_rawDescGZIP(), []int{8}
}

func (x *ListLeaguesResponse) GetLeagues() []*League {
	if x != nil {
		return x.Leagues
	}
	return nil
}

type ListEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SportId       string                 `protobuf:"bytes,1,opt,name=sport_id,json=sportId,proto3" json:"sport_id,omitempty"`
	LeagueId      string                 `protobuf:"bytes,2,opt,name=league_id,json=leagueId,proto3" json:"league_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Page          int32                  `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventsRequest) Reset() {
	*x = ListEventsRequest{}
	mi := &file_internal_proto_oddsfeed_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsRequest) ProtoMessage() {}

func (x *ListEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_oddsfeed_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventsRequest.ProtoReflect.Descriptor instead.
func (*ListEventsRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_oddsfeed_proto_rawDescGZIP(), []int{9}
}

func (x *ListEventsRequest) GetSportId() string {
	if x != nil {
		return x.SportId
	}
	return ""
}

func (x *ListEventsRequest) GetLeagueId() string {
	if x != nil {
		return x.LeagueId
	}
	return ""
}

func (x *ListEventsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListEventsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListEventsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventsResponse) Reset() {
	*x = ListEventsResponse{}
	mi := &file_internal_proto_oddsfeed_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsResponse) ProtoMessage() {}

func (x *ListEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_oddsfeed_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventsResponse.ProtoReflect.Descriptor instead.
func (*ListEventsResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_oddsfeed_proto_rawDescGZIP(), []int{10}
}

func (x *ListEventsResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

type GetEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventRequest) Reset() {
	*x = GetEventRequest{}
	mi := &file_internal_proto_oddsfeed_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventRequest) ProtoMessage() {}

func (x *GetEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_oddsfeed_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventRequest.ProtoReflect.Descriptor instead.
func (*GetEventRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_oddsfeed_proto_rawDescGZIP(), []int{11}
}

func (x *GetEventRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *Event                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventResponse) Reset() {
	*x = GetEventResponse{}
	mi := &file_internal_proto_oddsfeed_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventResponse) ProtoMessage() {}

func (x *GetEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_oddsfeed_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventResponse.ProtoReflect.Descriptor instead.
func (*GetEventResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_oddsfeed_proto_rawDescGZIP(), []int{12}
}

func (x *GetEventResponse) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

type ListMarketsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMarketsRequest) Reset() {
	*x = ListMarketsRequest{}
	mi := &file_internal_proto_oddsfeed_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMarketsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMarketsRequest) ProtoMessage() {}

func (x *ListMarketsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_oddsfeed_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMarketsRequest.ProtoReflect.Descriptor instead.
func (*ListMarketsRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_oddsfeed_proto_rawDescGZIP(), []int{13}
}

func (x *ListMarketsRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *ListMarketsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListMarketsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListMarketsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListMarketsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Markets       []*Market              `protobuf:"bytes,1,rep,name=markets,proto3" json:"markets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMarketsResponse) Reset() {
	*x = ListMarketsResponse{}
	mi := &file_internal_proto_oddsfeed_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMarketsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMarketsResponse) ProtoMessage() {}

func (x *ListMarketsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_oddsfeed_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMarketsResponse.ProtoReflect.Descriptor instead.
func (*ListMarketsResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_oddsfeed_proto_rawDescGZIP(), []int{14}
}

func (x *ListMarketsResponse) GetMarkets() []*Market {
	if x != nil {
		return x.Markets
	}
	return nil
}

type ListOutcomesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MarketId      string                 `protobuf:"bytes,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOutcomesRequest) Reset() {
	*x = ListOutcomesRequest{}
	mi := &file_internal_proto_oddsfeed_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOutcomesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOutcomesRequest) ProtoMessage() {}

func (x *ListOutcomesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_oddsfeed_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOutcomesRequest.ProtoReflect.Descriptor instead.
func (*ListOutcomesRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_oddsfeed_proto_rawDescGZIP(), []int{15}
}

func (x *ListOutcomesRequest) GetMarketId() string {
	if x != nil {
		return x.MarketId
	}
	return ""
}

func (x *ListOutcomesRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListOutcomesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListOutcomesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListOutcomesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Outcomes      []*Outcome             `protobuf:"bytes,1,rep,name=outcomes,proto3" json:"outcomes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOutcomesResponse) Reset() {
	*x = ListOutcomesResponse{}
	mi := &file_internal_proto_oddsfeed_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOutcomesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOutcomesResponse) ProtoMessage() {}

func (x *ListOutcomesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_oddsfeed_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOutcomesResponse.ProtoReflect.Descriptor instead.
func (*ListOutcomesResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_oddsfeed_proto_rawDescGZIP(), []int{16}
}

func (x *ListOutcomesResponse) GetOutcomes() []*Outcome {
	if x != nil {
		return x.Outcomes
	}
	return nil
}

type ListLiveScoresRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SportId       string                 `protobuf:"bytes,1,opt,name=sport_id,json=sportId,proto3" json:"sport_id,omitempty"`
	LeagueId      string                 `protobuf:"bytes,2,opt,name=league_id,json=leagueId,proto3" json:"league_id,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLiveScoresRequest) Reset() {
	*x = ListLiveScoresRequest{}
	mi := &file_internal_proto_oddsfeed_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLiveScoresRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLiveScoresRequest) ProtoMessage() {}

func (x *ListLiveScoresRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_oddsfeed_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLiveScoresRequest.ProtoReflect.Descriptor instead.
func (*ListLiveScoresRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_oddsfeed_proto_rawDescGZIP(), []int{17}
}

func (x *ListLiveScoresRequest) GetSportId() string {
	if x != nil {
		return x.SportId
	}
	return ""
}

func (x *ListLiveScoresRequest) GetLeagueId() string {
	if x != nil {
		return x.LeagueId
	}
	return ""
}

func (x *ListLiveScoresRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListLiveScoresRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListLiveScoresResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLiveScoresResponse) Reset() {
	*x = ListLiveScoresResponse{}
	mi := &file_internal_proto_oddsfeed_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLiveScoresResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLiveScoresResponse) ProtoMessage() {}

func (x *ListLiveScoresResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_oddsfeed_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLiveScoresResponse.ProtoReflect.Descriptor instead.
func (*ListLiveScoresResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_oddsfeed_proto_rawDescGZIP(), []int{18}
}

func (x *ListLiveScoresResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

var File_internal_proto_oddsfeed_proto protoreflect.FileDescriptor

const file_internal_proto_oddsfeed_proto_rawDesc = "" +
	"\n" +
	"\x1dinternal/proto/oddsfeed.proto\x12\boddsfeed\"?\n" +
	"\x05Sport\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug\"a\n" +
	"\x06League\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x19\n" +
	"\bsport_id\x18\x03 \x01(\tR\asportId\x12\x18\n" +
	"\acountry\x18\x04 \x01(\tR\acountry\"\xc2\x02\n" +
	"\x05Event\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tleague_id\x18\x02 \x01(\tR\bleagueId\x12\x19\n" +
	"\bsport_id\x18\x03 \x01(\tR\asportId\x12)\n" +
	"\x10home_participant\x18\x04 \x01(\tR\x0fhomeParticipant\x12)\n" +
	"\x10away_participant\x18\x05 \x01(\tR\x0fawayParticipant\x12\x1b\n" +
	"\tstarts_at\x18\x06 \x01(\tR\bstartsAt\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"home_score\x18\b \x01(\tR\thomeScore\x12\x1d\n" +
	"\n" +
	"away_score\x18\t \x01(\tR\tawayScore\x12(\n" +
	"\x10score_updated_at\x18\n" +
	" \x01(\tR\x0escoreUpdatedAt\"\x87\x01\n" +
	"\x06Market\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x12\n" +
	"\x04line\x18\x05 \x01(\tR\x04line\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\"v\n" +
	"\aOutcome\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tmarket_id\x18\x02 \x01(\tR\bmarketId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04odds\x18\x04 \x01(\tR\x04odds\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\"D\n" +
	"\x11ListSportsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"=\n" +
	"\x12ListSportsResponse\x12'\n" +
	"\x06sports\x18\x01 \x03(\v2\x0f.oddsfeed.SportR\x06sports\"`\n" +
	"\x12ListLeaguesRequest\x12\x19\n" +
	"\bsport_id\x18\x01 \x01(\tR\asportId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"A\n" +
	"\x13ListLeaguesResponse\x12*\n" +
	"\aleagues\x18\x01 \x03(\v2\x10.oddsfeed.LeagueR\aleagues\"\x94\x01\n" +
	"\x11ListEventsRequest\x12\x19\n" +
	"\bsport_id\x18\x01 \x01(\tR\asportId\x12\x1b\n" +
	"\tleague_id\x18\x02 \x01(\tR\bleagueId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x12\n" +
	"\x04page\x18\x04 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x05 \x01(\x05R\bpageSize\"=\n" +
	"\x12ListEventsResponse\x12'\n" +
	"\x06events\x18\x01 \x03(\v2\x0f.oddsfeed.EventR\x06events\"!\n" +
	"\x0fGetEventRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"9\n" +
	"\x10GetEventResponse\x12%\n" +
	"\x05event\x18\x01 \x01(\v2\x0f.oddsfeed.EventR\x05event\"x\n" +
	"\x12ListMarketsRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"A\n" +
	"\x13ListMarketsResponse\x12*\n" +
	"\amarkets\x18\x01 \x03(\v2\x10.oddsfeed.MarketR\amarkets\"{\n" +
	"\x13ListOutcomesRequest\x12\x1b\n" +
	"\tmarket_id\x18\x01 \x01(\tR\bmarketId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"E\n" +
	"\x14ListOutcomesResponse\x12-\n" +
	"\boutcomes\x18\x01 \x03(\v2\x11.oddsfeed.OutcomeR\boutcomes\"\x80\x01\n" +
	"\x15ListLiveScoresRequest\x12\x19\n" +
	"\bsport_id\x18\x01 \x01(\tR\asportId\x12\x1b\n" +
	"\tleague_id\x18\x02 \x01(\tR\bleagueId\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"A\n" +
	"\x16ListLiveScoresResponse\x12'\n" +
	"\x06events\x18\x01 \x03(\v2\x0f.oddsfeed.EventR\x06events2\xa2\x04\n" +
	"\x0fOddsFeedService\x12G\n" +
	"\n" +
	"ListSports\x12\x1b.oddsfeed.ListSportsRequest\x1a\x1c.oddsfeed.ListSportsResponse\x12J\n" +
	"\vListLeagues\x12\x1c.oddsfeed.ListLeaguesRequest\x1a\x1d.oddsfeed.ListLeaguesResponse\x12G\n" +
	"\n" +
	"ListEvents\x12\x1b.oddsfeed.ListEventsRequest\x1a\x1c.oddsfeed.ListEventsResponse\x12A\n" +
	"\bGetEvent\x12\x19.oddsfeed.GetEventRequest\x1a\x1a.oddsfeed.GetEventResponse\x12J\n" +
	"\vListMarkets\x12\x1c.oddsfeed.ListMarketsRequest\x1a\x1d.oddsfeed.ListMarketsResponse\x12M\n" +
	"\fListOutcomes\x12\x1d.oddsfeed.ListOutcomesRequest\x1a\x1e.oddsfeed.ListOutcomesResponse\x12S\n" +
	"\x0eListLiveScores\x12\x1f.oddsfeed.ListLiveScoresRequest\x1a .oddsfeed.ListLiveScoresResponseB8Z6github.com/realyoussefhossam/betmonster/internal/protob\x06proto3"

var (
	file_internal_proto_oddsfeed_proto_rawDescOnce sync.Once
	file_internal_proto_oddsfeed_proto_rawDescData []byte
)

func file_internal_proto_oddsfeed_proto_rawDescGZIP() []byte {
	file_internal_proto_oddsfeed_proto_rawDescOnce.Do(func() {
		file_internal_proto_oddsfeed_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_oddsfeed_proto_rawDesc), len(file_internal_proto_oddsfeed_proto_rawDesc)))
	})
	return file_internal_proto_oddsfeed_proto_rawDescData
}

var file_internal_proto_oddsfeed_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_internal_proto_oddsfeed_proto_goTypes = []any{
	(*Sport)(nil),                  // 0: oddsfeed.Sport
	(*League)(nil),                 // 1: oddsfeed.League
	(*Event)(nil),                  // 2: oddsfeed.Event
	(*Market)(nil),                 // 3: oddsfeed.Market
	(*Outcome)(nil),                // 4: oddsfeed.Outcome
	(*ListSportsRequest)(nil),      // 5: oddsfeed.ListSportsRequest
	(*ListSportsResponse)(nil),     // 6: oddsfeed.ListSportsResponse
	(*ListLeaguesRequest)(nil),     // 7: oddsfeed.ListLeaguesRequest
	(*ListLeaguesResponse)(nil),    // 8: oddsfeed.ListLeaguesResponse
	(*ListEventsRequest)(nil),      // 9: oddsfeed.ListEventsRequest
	(*ListEventsResponse)(nil),     // 10: oddsfeed.ListEventsResponse
	(*GetEventRequest)(nil),        // 11: oddsfeed.GetEventRequest
	(*GetEventResponse)(nil),       // 12: oddsfeed.GetEventResponse
	(*ListMarketsRequest)(nil),     // 13: oddsfeed.ListMarketsRequest
	(*ListMarketsResponse)(nil),    // 14: oddsfeed.ListMarketsResponse
	(*ListOutcomesRequest)(nil),    // 15: oddsfeed.ListOutcomesRequest
	(*ListOutcomesResponse)(nil),   // 16: oddsfeed.ListOutcomesResponse
	(*ListLiveScoresRequest)(nil),  // 17: oddsfeed.ListLiveScoresRequest
	(*ListLiveScoresResponse)(nil), // 18: oddsfeed.ListLiveScoresResponse
}
var file_internal_proto_oddsfeed_proto_depIdxs = []int32{
	0,  // 0: oddsfeed.ListSportsResponse.sports:type_name -> oddsfeed.Sport
	1,  // 1: oddsfeed.ListLeaguesResponse.leagues:type_name -> oddsfeed.League
	2,  // 2: oddsfeed.ListEventsResponse.events:type_name -> oddsfeed.Event
	2,  // 3: oddsfeed.GetEventResponse.event:type_name -> oddsfeed.Event
	3,  // 4: oddsfeed.ListMarketsResponse.markets:type_name -> oddsfeed.Market
	4,  // 5: oddsfeed.ListOutcomesResponse.outcomes:type_name -> oddsfeed.Outcome
	2,  // 6: oddsfeed.ListLiveScoresResponse.events:type_name -> oddsfeed.Event
	5,  // 7: oddsfeed.OddsFeedService.ListSports:input_type -> oddsfeed.ListSportsRequest
	7,  // 8: oddsfeed.OddsFeedService.ListLeagues:input_type -> oddsfeed.ListLeaguesRequest
	9,  // 9: oddsfeed.OddsFeedService.ListEvents:input_type -> oddsfeed.ListEventsRequest
	11, // 10: oddsfeed.OddsFeedService.GetEvent:input_type -> oddsfeed.GetEventRequest
	13, // 11: oddsfeed.OddsFeedService.ListMarkets:input_type -> oddsfeed.ListMarketsRequest
	15, // 12: oddsfeed.OddsFeedService.ListOutcomes:input_type -> oddsfeed.ListOutcomesRequest
	17, // 13: oddsfeed.OddsFeedService.ListLiveScores:input_type -> oddsfeed.ListLiveScoresRequest
	6,  // 14: oddsfeed.OddsFeedService.ListSports:output_type -> oddsfeed.ListSportsResponse
	8,  // 15: oddsfeed.OddsFeedService.ListLeagues:output_type -> oddsfeed.ListLeaguesResponse
	10, // 16: oddsfeed.OddsFeedService.ListEvents:output_type -> oddsfeed.ListEventsResponse
	12, // 17: oddsfeed.OddsFeedService.GetEvent:output_type -> oddsfeed.GetEventResponse
	14, // 18: oddsfeed.OddsFeedService.ListMarkets:output_type -> oddsfeed.ListMarketsResponse
	16, // 19: oddsfeed.OddsFeedService.ListOutcomes:output_type -> oddsfeed.ListOutcomesResponse
	18, // 20: oddsfeed.OddsFeedService.ListLiveScores:output_type -> oddsfeed.ListLiveScoresResponse
	14, // [14:21] is the sub-list for method output_type
	7,  // [7:14] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_internal_proto_oddsfeed_proto_init() }
func file_internal_proto_oddsfeed_proto_init() {
	if File_internal_proto_oddsfeed_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_oddsfeed_proto_rawDesc), len(file_internal_proto_oddsfeed_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_oddsfeed_proto_goTypes,
		DependencyIndexes: file_internal_proto_oddsfeed_proto_depIdxs,
		MessageInfos:      file_internal_proto_oddsfeed_proto_msgTypes,
	}.Build()
	File_internal_proto_oddsfeed_proto = out.File
	file_internal_proto_oddsfeed_proto_goTypes = nil
	file_internal_proto_oddsfeed_proto_depIdxs = nil
}
