// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: internal/proto/oddsfeed.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OddsFeedService_ListSports_FullMethodName     = "/oddsfeed.OddsFeedService/ListSports"
	OddsFeedService_ListLeagues_FullMethodName    = "/oddsfeed.OddsFeedService/ListLeagues"
	OddsFeedService_ListEvents_FullMethodName     = "/oddsfeed.OddsFeedService/ListEvents"
	OddsFeedService_GetEvent_FullMethodName       = "/oddsfeed.OddsFeedService/GetEvent"
	OddsFeedService_ListMarkets_FullMethodName    = "/oddsfeed.OddsFeedService/ListMarkets"
	OddsFeedService_ListOutcomes_FullMethodName   = "/oddsfeed.OddsFeedService/ListOutcomes"
	OddsFeedService_ListLiveScores_FullMethodName = "/oddsfeed.OddsFeedService/ListLiveScores"
)

// OddsFeedServiceClient is the client API for OddsFeedService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OddsFeedServiceClient interface {
	ListSports(ctx context.Context, in *ListSportsRequest, opts ...grpc.CallOption) (*ListSportsResponse, error)
	ListLeagues(ctx context.Context, in *ListLeaguesRequest, opts ...grpc.CallOption) (*ListLeaguesResponse, error)
	ListEvents(ctx context.Context, in *ListEventsRequest, opts ...grpc.CallOption) (*ListEventsResponse, error)
	GetEvent(ctx context.Context, in *GetEventRequest, opts ...grpc.CallOption) (*GetEventResponse, error)
	ListMarkets(ctx context.Context, in *ListMarketsRequest, opts ...grpc.CallOption) (*ListMarketsResponse, error)
	ListOutcomes(ctx context.Context, in *ListOutcomesRequest, opts ...grpc.CallOption) (*ListOutcomesResponse, error)
	ListLiveScores(ctx context.Context, in *ListLiveScoresRequest, opts ...grpc.CallOption) (*ListLiveScoresResponse, error)
}

type oddsFeedServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOddsFeedServiceClient(cc grpc.ClientConnInterface) OddsFeedServiceClient {
	return &oddsFeedServiceClient{cc}
}

func (c *oddsFeedServiceClient) ListSports(ctx context.Context, in *ListSportsRequest, opts ...grpc.CallOption) (*ListSportsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSportsResponse)
	err := c.cc.Invoke(ctx, OddsFeedService_ListSports_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oddsFeedServiceClient) ListLeagues(ctx context.Context, in *ListLeaguesRequest, opts ...grpc.CallOption) (*ListLeaguesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListLeaguesResponse)
	err := c.cc.Invoke(ctx, OddsFeedService_ListLeagues_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oddsFeedServiceClient) ListEvents(ctx context.Context, in *ListEventsRequest, opts ...grpc.CallOption) (*ListEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListEventsResponse)
	err := c.cc.Invoke(ctx, OddsFeedService_ListEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oddsFeedServiceClient) GetEvent(ctx context.Context, in *GetEventRequest, opts ...grpc.CallOption) (*GetEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEventResponse)
	err := c.cc.Invoke(ctx, OddsFeedService_GetEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oddsFeedServiceClient) ListMarkets(ctx context.Context, in *ListMarketsRequest, opts ...grpc.CallOption) (*ListMarketsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMarketsResponse)
	err := c.cc.Invoke(ctx, OddsFeedService_ListMarkets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oddsFeedServiceClient) ListOutcomes(ctx context.Context, in *ListOutcomesRequest, opts ...grpc.CallOption) (*ListOutcomesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListOutcomesResponse)
	err := c.cc.Invoke(ctx, OddsFeedService_ListOutcomes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oddsFeedServiceClient) ListLiveScores(ctx context.Context, in *ListLiveScoresRequest, opts ...grpc.CallOption) (*ListLiveScoresResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListLiveScoresResponse)
	err := c.cc.Invoke(ctx, OddsFeedService_ListLiveScores_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OddsFeedServiceServer is the server API for OddsFeedService service.
// All implementations must embed UnimplementedOddsFeedServiceServer
// for forward compatibility.
type OddsFeedServiceServer interface {
	ListSports(context.Context, *ListSportsRequest) (*ListSportsResponse, error)
	ListLeagues(context.Context, *ListLeaguesRequest) (*ListLeaguesResponse, error)
	ListEvents(context.Context, *ListEventsRequest) (*ListEventsResponse, error)
	GetEvent(context.Context, *GetEventRequest) (*GetEventResponse, error)
	ListMarkets(context.Context, *ListMarketsRequest) (*ListMarketsResponse, error)
	ListOutcomes(context.Context, *ListOutcomesRequest) (*ListOutcomesResponse, error)
	ListLiveScores(context.Context, *ListLiveScoresRequest) (*ListLiveScoresResponse, error)
	mustEmbedUnimplementedOddsFeedServiceServer()
}

// UnimplementedOddsFeedServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOddsFeedServiceServer struct{}

func (UnimplementedOddsFeedServiceServer) ListSports(context.Context, *ListSportsRequest) (*ListSportsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSports not implemented")
}
func (UnimplementedOddsFeedServiceServer) ListLeagues(context.Context, *ListLeaguesRequest) (*ListLeaguesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListLeagues not implemented")
}
func (UnimplementedOddsFeedServiceServer) ListEvents(context.Context, *ListEventsRequest) (*ListEventsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListEvents not implemented")
}
func (UnimplementedOddsFeedServiceServer) GetEvent(context.Context, *GetEventRequest) (*GetEventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEvent not implemented")
}
func (UnimplementedOddsFeedServiceServer) ListMarkets(context.Context, *ListMarketsRequest) (*ListMarketsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMarkets not implemented")
}
func (UnimplementedOddsFeedServiceServer) ListOutcomes(context.Context, *ListOutcomesRequest) (*ListOutcomesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListOutcomes not implemented")
}
func (UnimplementedOddsFeedServiceServer) ListLiveScores(context.Context, *ListLiveScoresRequest) (*ListLiveScoresResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListLiveScores not implemented")
}
func (UnimplementedOddsFeedServiceServer) mustEmbedUnimplementedOddsFeedServiceServer() {}
func (UnimplementedOddsFeedServiceServer) testEmbeddedByValue()                         {}

// UnsafeOddsFeedServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OddsFeedServiceServer will
// result in compilation errors.
type UnsafeOddsFeedServiceServer interface {
	mustEmbedUnimplementedOddsFeedServiceServer()
}

func RegisterOddsFeedServiceServer(s grpc.ServiceRegistrar, srv OddsFeedServiceServer) {
	// If the following call panics, it indicates UnimplementedOddsFeedServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OddsFeedService_ServiceDesc, srv)
}

func _OddsFeedService_ListSports_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSportsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OddsFeedServiceServer).ListSports(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OddsFeedService_ListSports_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OddsFeedServiceServer).ListSports(ctx, req.(*ListSportsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OddsFeedService_ListLeagues_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLeaguesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OddsFeedServiceServer).ListLeagues(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OddsFeedService_ListLeagues_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OddsFeedServiceServer).ListLeagues(ctx, req.(*ListLeaguesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OddsFeedService_ListEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OddsFeedServiceServer).ListEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OddsFeedService_ListEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OddsFeedServiceServer).ListEvents(ctx, req.(*ListEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OddsFeedService_GetEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OddsFeedServiceServer).GetEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OddsFeedService_GetEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OddsFeedServiceServer).GetEvent(ctx, req.(*GetEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OddsFeedService_ListMarkets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMarketsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OddsFeedServiceServer).ListMarkets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OddsFeedService_ListMarkets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OddsFeedServiceServer).ListMarkets(ctx, req.(*ListMarketsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OddsFeedService_ListOutcomes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOutcomesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OddsFeedServiceServer).ListOutcomes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OddsFeedService_ListOutcomes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OddsFeedServiceServer).ListOutcomes(ctx, req.(*ListOutcomesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OddsFeedService_ListLiveScores_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLiveScoresRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OddsFeedServiceServer).ListLiveScores(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OddsFeedService_ListLiveScores_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OddsFeedServiceServer).ListLiveScores(ctx, req.(*ListLiveScoresRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OddsFeedService_ServiceDesc is the grpc.ServiceDesc for OddsFeedService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OddsFeedService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "oddsfeed.OddsFeedService",
	HandlerType: (*OddsFeedServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListSports",
			Handler:    _OddsFeedService_ListSports_Handler,
		},
		{
			MethodName: "ListLeagues",
			Handler:    _OddsFeedService_ListLeagues_Handler,
		},
		{
			MethodName: "ListEvents",
			Handler:    _OddsFeedService_ListEvents_Handler,
		},
		{
			MethodName: "GetEvent",
			Handler:    _OddsFeedService_GetEvent_Handler,
		},
		{
			MethodName: "ListMarkets",
			Handler:    _OddsFeedService_ListMarkets_Handler,
		},
		{
			MethodName: "ListOutcomes",
			Handler:    _OddsFeedService_ListOutcomes_Handler,
		},
		{
			MethodName: "ListLiveScores",
			Handler:    _OddsFeedService_ListLiveScores_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/proto/oddsfeed.proto",
}
