// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: internal/proto/sportsbook.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OddsSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OutcomeId     string                 `protobuf:"bytes,1,opt,name=outcome_id,json=outcomeId,proto3" json:"outcome_id,omitempty"`
	Odds          string                 `protobuf:"bytes,2,opt,name=odds,proto3" json:"odds,omitempty"` // decimal string, e.g. "2.10"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OddsSnapshot) Reset() {
	*x = OddsSnapshot{}
	mi := &file_internal_proto_sportsbook_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OddsSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OddsSnapshot) ProtoMessage() {}

func (x *OddsSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_sportsbook_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OddsSnapshot.ProtoReflect.Descriptor instead.
func (*OddsSnapshot) Descriptor() ([]byte, []int) {
	return file_internal_proto_sportsbook_proto_rawDescGZIP(), []int{0}
}

func (x *OddsSnapshot) GetOutcomeId() string {
	if x != nil {
		return x.OutcomeId
	}
	return ""
}

func (x *OddsSnapshot) GetOdds() string {
	if x != nil {
		return x.Odds
	}
	return ""
}

type Bet struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId          string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	EventId         string                 `protobuf:"bytes,3,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	MarketId        string                 `protobuf:"bytes,4,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	OutcomeId       string                 `protobuf:"bytes,5,opt,name=outcome_id,json=outcomeId,proto3" json:"outcome_id,omitempty"`
	Odds            string                 `protobuf:"bytes,6,opt,name=odds,proto3" json:"odds,omitempty"`
	Stake           string                 `protobuf:"bytes,7,opt,name=stake,proto3" json:"stake,omitempty"` // decimal string
	PotentialPayout string                 `protobuf:"bytes,8,opt,name=potential_payout,json=potentialPayout,proto3" json:"potential_payout,omitempty"`
	Currency        string                 `protobuf:"bytes,9,opt,name=currency,proto3" json:"currency,omitempty"`
	Status          string                 `protobuf:"bytes,10,opt,name=status,proto3" json:"status,omitempty"` // pending, won, lost, cancelled, settled
	ReferenceId     string                 `protobuf:"bytes,11,opt,name=reference_id,json=referenceId,proto3" json:"reference_id,omitempty"`
	CreatedAt       string                 `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	SettledAt       string                 `protobuf:"bytes,13,opt,name=settled_at,json=settledAt,proto3" json:"settled_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Bet) Reset() {
	*x = Bet{}
	mi := &file_internal_proto_sportsbook_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bet) ProtoMessage() {}

func (x *Bet) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_sportsbook_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bet.ProtoReflect.Descriptor instead.
func (*Bet) Descriptor() ([]byte, []int) {
	return file_internal_proto_sportsbook_proto_rawDescGZIP(), []int{1}
}

func (x *Bet) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Bet) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Bet) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *Bet) GetMarketId() string {
	if x != nil {
		return x.MarketId
	}
	return ""
}

func (x *Bet) GetOutcomeId() string {
	if x != nil {
		return x.OutcomeId
	}
	return ""
}

func (x *Bet) GetOdds() string {
	if x != nil {
		return x.Odds
	}
	return ""
}

func (x *Bet) GetStake() string {
	if x != nil {
		return x.Stake
	}
	return ""
}

func (x *Bet) GetPotentialPayout() string {
	if x != nil {
		return x.PotentialPayout
	}
	return ""
}

func (x *Bet) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Bet) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Bet) GetReferenceId() string {
	if x != nil {
		return x.ReferenceId
	}
	return ""
}

func (x *Bet) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Bet) GetSettledAt() string {
	if x != nil {
		return x.SettledAt
	}
	return ""
}

type PlaceBetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	EventId       string                 `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	MarketId      string                 `protobuf:"bytes,3,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	OutcomeId     string                 `protobuf:"bytes,4,opt,name=outcome_id,json=outcomeId,proto3" json:"outcome_id,omitempty"`
	Stake         string                 `protobuf:"bytes,5,opt,name=stake,proto3" json:"stake,omitempty"`
	Currency      string                 `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	ReferenceId   string                 `protobuf:"bytes,7,opt,name=reference_id,json=referenceId,proto3" json:"reference_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaceBetRequest) Reset() {
	*x = PlaceBetRequest{}
	mi := &file_internal_proto_sportsbook_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceBetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceBetRequest) ProtoMessage() {}

func (x *PlaceBetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_sportsbook_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceBetRequest.ProtoReflect.Descriptor instead.
func (*PlaceBetRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_sportsbook_proto_rawDescGZIP(), []int{2}
}

func (x *PlaceBetRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PlaceBetRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *PlaceBetRequest) GetMarketId() string {
	if x != nil {
		return x.MarketId
	}
	return ""
}

func (x *PlaceBetRequest) GetOutcomeId() string {
	if x != nil {
		return x.OutcomeId
	}
	return ""
}

func (x *PlaceBetRequest) GetStake() string {
	if x != nil {
		return x.Stake
	}
	return ""
}

func (x *PlaceBetRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *PlaceBetRequest) GetReferenceId() string {
	if x != nil {
		return x.ReferenceId
	}
	return ""
}

type PlaceBetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bet           *Bet                   `protobuf:"bytes,1,opt,name=bet,proto3" json:"bet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaceBetResponse) Reset() {
	*x = PlaceBetResponse{}
	mi := &file_internal_proto_sportsbook_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceBetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceBetResponse) ProtoMessage() {}

func (x *PlaceBetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_sportsbook_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceBetResponse.ProtoReflect.Descriptor instead.
func (*PlaceBetResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_sportsbook_proto_rawDescGZIP(), []int{3}
}

func (x *PlaceBetResponse) GetBet() *Bet {
	if x != nil {
		return x.Bet
	}
	return nil
}

type GetBetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBetRequest) Reset() {
	*x = GetBetRequest{}
	mi := &file_internal_proto_sportsbook_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBetRequest) ProtoMessage() {}

func (x *GetBetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_sportsbook_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBetRequest.ProtoReflect.Descriptor instead.
func (*GetBetRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_sportsbook_proto_rawDescGZIP(), []int{4}
}

func (x *GetBetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetBetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bet           *Bet                   `protobuf:"bytes,1,opt,name=bet,proto3" json:"bet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBetResponse) Reset() {
	*x = GetBetResponse{}
	mi := &file_internal_proto_sportsbook_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBetResponse) ProtoMessage() {}

func (x *GetBetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_sportsbook_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBetResponse.ProtoReflect.Descriptor instead.
func (*GetBetResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_sportsbook_proto_rawDescGZIP(), []int{5}
}

func (x *GetBetResponse) GetBet() *Bet {
	if x != nil {
		return x.Bet
	}
	return nil
}

type ListBetsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBetsRequest) Reset() {
	*x = ListBetsRequest{}
	mi := &file_internal_proto_sportsbook_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBetsRequest) ProtoMessage() {}

func (x *ListBetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_sportsbook_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBetsRequest.ProtoReflect.Descriptor instead.
func (*ListBetsRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_sportsbook_proto_rawDescGZIP(), []int{6}
}

func (x *ListBetsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListBetsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListBetsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListBetsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListBetsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bets          []*Bet                 `protobuf:"bytes,1,rep,name=bets,proto3" json:"bets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBetsResponse) Reset() {
	*x = ListBetsResponse{}
	mi := &file_internal_proto_sportsbook_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBetsResponse) ProtoMessage() {}

func (x *ListBetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_sportsbook_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBetsResponse.ProtoReflect.Descriptor instead.
func (*ListBetsResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_sportsbook_proto_rawDescGZIP(), []int{7}
}

func (x *ListBetsResponse) GetBets() []*Bet {
	if x != nil {
		return x.Bets
	}
	return nil
}

type SettleBetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BetId         string                 `protobuf:"bytes,1,opt,name=bet_id,json=betId,proto3" json:"bet_id,omitempty"`
	Outcome       string                 `protobuf:"bytes,2,opt,name=outcome,proto3" json:"outcome,omitempty"` // won, lost, cancelled
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettleBetRequest) Reset() {
	*x = SettleBetRequest{}
	mi := &file_internal_proto_sportsbook_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettleBetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettleBetRequest) ProtoMessage() {}

func (x *SettleBetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_sportsbook_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettleBetRequest.ProtoReflect.Descriptor instead.
func (*SettleBetRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_sportsbook_proto_rawDescGZIP(), []int{8}
}

func (x *SettleBetRequest) GetBetId() string {
	if x != nil {
		return x.BetId
	}
	return ""
}

func (x *SettleBetRequest) GetOutcome() string {
	if x != nil {
		return x.Outcome
	}
	return ""
}

type SettleBetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bet           *Bet                   `protobuf:"bytes,1,opt,name=bet,proto3" json:"bet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettleBetResponse) Reset() {
	*x = SettleBetResponse{}
	mi := &file_internal_proto_sportsbook_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettleBetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettleBetResponse) ProtoMessage() {}

func (x *SettleBetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_sportsbook_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettleBetResponse.ProtoReflect.Descriptor instead.
func (*SettleBetResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_sportsbook_proto_rawDescGZIP(), []int{9}
}

func (x *SettleBetResponse) GetBet() *Bet {
	if x != nil {
		return x.Bet
	}
	return nil
}

var File_internal_proto_sportsbook_proto protoreflect.FileDescriptor

const file_internal_proto_sportsbook_proto_rawDesc = "" +
	"\n" +
	"\x1finternal/proto/sportsbook.proto\x12\n" +
	"sportsbook\"A\n" +
	"\fOddsSnapshot\x12\x1d\n" +
	"\n" +
	"outcome_id\x18\x01 \x01(\tR\toutcomeId\x12\x12\n" +
	"\x04odds\x18\x02 \x01(\tR\x04odds\"\xef\x02\n" +
	"\x03Bet\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x19\n" +
	"\bevent_id\x18\x03 \x01(\tR\aeventId\x12\x1b\n" +
	"\tmarket_id\x18\x04 \x01(\tR\bmarketId\x12\x1d\n" +
	"\n" +
	"outcome_id\x18\x05 \x01(\tR\toutcomeId\x12\x12\n" +
	"\x04odds\x18\x06 \x01(\tR\x04odds\x12\x14\n" +
	"\x05stake\x18\a \x01(\tR\x05stake\x12)\n" +
	"\x10potential_payout\x18\b \x01(\tR\x0fpotentialPayout\x12\x1a\n" +
	"\bcurrency\x18\t \x01(\tR\bcurrency\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\tR\x06status\x12!\n" +
	"\freference_id\x18\v \x01(\tR\vreferenceId\x12\x1d\n" +
	"\n" +
	"created_at\x18\f \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"settled_at\x18\r \x01(\tR\tsettledAt\"\xd6\x01\n" +
	"\x0fPlaceBetRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventId\x12\x1b\n" +
	"\tmarket_id\x18\x03 \x01(\tR\bmarketId\x12\x1d\n" +
	"\n" +
	"outcome_id\x18\x04 \x01(\tR\toutcomeId\x12\x14\n" +
	"\x05stake\x18\x05 \x01(\tR\x05stake\x12\x1a\n" +
	"\bcurrency\x18\x06 \x01(\tR\bcurrency\x12!\n" +
	"\freference_id\x18\a \x01(\tR\vreferenceId\"5\n" +
	"\x10PlaceBetResponse\x12!\n" +
	"\x03bet\x18\x01 \x01(\v2\x0f.sportsbook.BetR\x03bet\"\x1f\n" +
	"\rGetBetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"3\n" +
	"\x0eGetBetResponse\x12!\n" +
	"\x03bet\x18\x01 \x01(\v2\x0f.sportsbook.BetR\x03bet\"s\n" +
	"\x0fListBetsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"7\n" +
	"\x10ListBetsResponse\x12#\n" +
	"\x04bets\x18\x01 \x03(\v2\x0f.sportsbook.BetR\x04bets\"C\n" +
	"\x10SettleBetRequest\x12\x15\n" +
	"\x06bet_id\x18\x01 \x01(\tR\x05betId\x12\x18\n" +
	"\aoutcome\x18\x02 \x01(\tR\aoutcome\"6\n" +
	"\x11SettleBetResponse\x12!\n" +
	"\x03bet\x18\x01 \x01(\v2\x0f.sportsbook.BetR\x03bet2\xac\x02\n" +
	"\x11SportsbookService\x12E\n" +
	"\bPlaceBet\x12\x1b.sportsbook.PlaceBetRequest\x1a\x1c.sportsbook.PlaceBetResponse\x12?\n" +
	"\x06GetBet\x12\x19.sportsbook.GetBetRequest\x1a\x1a.sportsbook.GetBetResponse\x12E\n" +
	"\bListBets\x12\x1b.sportsbook.ListBetsRequest\x1a\x1c.sportsbook.ListBetsResponse\x12H\n" +
	"\tSettleBet\x12\x1c.sportsbook.SettleBetRequest\x1a\x1d.sportsbook.SettleBetResponseB8Z6github.com/realyoussefhossam/betmonster/internal/protob\x06proto3"

var (
	file_internal_proto_sportsbook_proto_rawDescOnce sync.Once
	file_internal_proto_sportsbook_proto_rawDescData []byte
)

func file_internal_proto_sportsbook_proto_rawDescGZIP() []byte {
	file_internal_proto_sportsbook_proto_rawDescOnce.Do(func() {
		file_internal_proto_sportsbook_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_sportsbook_proto_rawDesc), len(file_internal_proto_sportsbook_proto_rawDesc)))
	})
	return file_internal_proto_sportsbook_proto_rawDescData
}

var file_internal_proto_sportsbook_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_internal_proto_sportsbook_proto_goTypes = []any{
	(*OddsSnapshot)(nil),      // 0: sportsbook.OddsSnapshot
	(*Bet)(nil),               // 1: sportsbook.Bet
	(*PlaceBetRequest)(nil),   // 2: sportsbook.PlaceBetRequest
	(*PlaceBetResponse)(nil),  // 3: sportsbook.PlaceBetResponse
	(*GetBetRequest)(nil),     // 4: sportsbook.GetBetRequest
	(*GetBetResponse)(nil),    // 5: sportsbook.GetBetResponse
	(*ListBetsRequest)(nil),   // 6: sportsbook.ListBetsRequest
	(*ListBetsResponse)(nil),  // 7: sportsbook.ListBetsResponse
	(*SettleBetRequest)(nil),  // 8: sportsbook.SettleBetRequest
	(*SettleBetResponse)(nil), // 9: sportsbook.SettleBetResponse
}
var file_internal_proto_sportsbook_proto_depIdxs = []int32{
	1, // 0: sportsbook.PlaceBetResponse.bet:type_name -> sportsbook.Bet
	1, // 1: sportsbook.GetBetResponse.bet:type_name -> sportsbook.Bet
	1, // 2: sportsbook.ListBetsResponse.bets:type_name -> sportsbook.Bet
	1, // 3: sportsbook.SettleBetResponse.bet:type_name -> sportsbook.Bet
	2, // 4: sportsbook.SportsbookService.PlaceBet:input_type -> sportsbook.PlaceBetRequest
	4, // 5: sportsbook.SportsbookService.GetBet:input_type -> sportsbook.GetBetRequest
	6, // 6: sportsbook.SportsbookService.ListBets:input_type -> sportsbook.ListBetsRequest
	8, // 7: sportsbook.SportsbookService.SettleBet:input_type -> sportsbook.SettleBetRequest
	3, // 8: sportsbook.SportsbookService.PlaceBet:output_type -> sportsbook.PlaceBetResponse
	5, // 9: sportsbook.SportsbookService.GetBet:output_type -> sportsbook.GetBetResponse
	7, // 10: sportsbook.SportsbookService.ListBets:output_type -> sportsbook.ListBetsResponse
	9, // 11: sportsbook.SportsbookService.SettleBet:output_type -> sportsbook.SettleBetResponse
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_internal_proto_sportsbook_proto_init() }
func file_internal_proto_sportsbook_proto_init() {
	if File_internal_proto_sportsbook_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_sportsbook_proto_rawDesc), len(file_internal_proto_sportsbook_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_sportsbook_proto_goTypes,
		DependencyIndexes: file_internal_proto_sportsbook_proto_depIdxs,
		MessageInfos:      file_internal_proto_sportsbook_proto_msgTypes,
	}.Build()
	File_internal_proto_sportsbook_proto = out.File
	file_internal_proto_sportsbook_proto_goTypes = nil
	file_internal_proto_sportsbook_proto_depIdxs = nil
}
