// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: internal/proto/sportsbook.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SportsbookService_PlaceBet_FullMethodName  = "/sportsbook.SportsbookService/PlaceBet"
	SportsbookService_GetBet_FullMethodName    = "/sportsbook.SportsbookService/GetBet"
	SportsbookService_ListBets_FullMethodName  = "/sportsbook.SportsbookService/ListBets"
	SportsbookService_SettleBet_FullMethodName = "/sportsbook.SportsbookService/SettleBet"
)

// SportsbookServiceClient is the client API for SportsbookService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SportsbookServiceClient interface {
	PlaceBet(ctx context.Context, in *PlaceBetRequest, opts ...grpc.CallOption) (*PlaceBetResponse, error)
	GetBet(ctx context.Context, in *GetBetRequest, opts ...grpc.CallOption) (*GetBetResponse, error)
	ListBets(ctx context.Context, in *ListBetsRequest, opts ...grpc.CallOption) (*ListBetsResponse, error)
	SettleBet(ctx context.Context, in *SettleBetRequest, opts ...grpc.CallOption) (*SettleBetResponse, error)
}

type sportsbookServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSportsbookServiceClient(cc grpc.ClientConnInterface) SportsbookServiceClient {
	return &sportsbookServiceClient{cc}
}

func (c *sportsbookServiceClient) PlaceBet(ctx context.Context, in *PlaceBetRequest, opts ...grpc.CallOption) (*PlaceBetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlaceBetResponse)
	err := c.cc.Invoke(ctx, SportsbookService_PlaceBet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sportsbookServiceClient) GetBet(ctx context.Context, in *GetBetRequest, opts ...grpc.CallOption) (*GetBetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBetResponse)
	err := c.cc.Invoke(ctx, SportsbookService_GetBet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sportsbookServiceClient) ListBets(ctx context.Context, in *ListBetsRequest, opts ...grpc.CallOption) (*ListBetsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBetsResponse)
	err := c.cc.Invoke(ctx, SportsbookService_ListBets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sportsbookServiceClient) SettleBet(ctx context.Context, in *SettleBetRequest, opts ...grpc.CallOption) (*SettleBetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SettleBetResponse)
	err := c.cc.Invoke(ctx, SportsbookService_SettleBet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SportsbookServiceServer is the server API for SportsbookService service.
// All implementations must embed UnimplementedSportsbookServiceServer
// for forward compatibility.
type SportsbookServiceServer interface {
	PlaceBet(context.Context, *PlaceBetRequest) (*PlaceBetResponse, error)
	GetBet(context.Context, *GetBetRequest) (*GetBetResponse, error)
	ListBets(context.Context, *ListBetsRequest) (*ListBetsResponse, error)
	SettleBet(context.Context, *SettleBetRequest) (*SettleBetResponse, error)
	mustEmbedUnimplementedSportsbookServiceServer()
}

// UnimplementedSportsbookServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSportsbookServiceServer struct{}

func (UnimplementedSportsbookServiceServer) PlaceBet(context.Context, *PlaceBetRequest) (*PlaceBetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PlaceBet not implemented")
}
func (UnimplementedSportsbookServiceServer) GetBet(context.Context, *GetBetRequest) (*GetBetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBet not implemented")
}
func (UnimplementedSportsbookServiceServer) ListBets(context.Context, *ListBetsRequest) (*ListBetsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBets not implemented")
}
func (UnimplementedSportsbookServiceServer) SettleBet(context.Context, *SettleBetRequest) (*SettleBetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SettleBet not implemented")
}
func (UnimplementedSportsbookServiceServer) mustEmbedUnimplementedSportsbookServiceServer() {}
func (UnimplementedSportsbookServiceServer) testEmbeddedByValue()                           {}

// UnsafeSportsbookServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SportsbookServiceServer will
// result in compilation errors.
type UnsafeSportsbookServiceServer interface {
	mustEmbedUnimplementedSportsbookServiceServer()
}

func RegisterSportsbookServiceServer(s grpc.ServiceRegistrar, srv SportsbookServiceServer) {
	// If the following call panics, it indicates UnimplementedSportsbookServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SportsbookService_ServiceDesc, srv)
}

func _SportsbookService_PlaceBet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlaceBetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SportsbookServiceServer).PlaceBet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SportsbookService_PlaceBet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SportsbookServiceServer).PlaceBet(ctx, req.(*PlaceBetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SportsbookService_GetBet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SportsbookServiceServer).GetBet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SportsbookService_GetBet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SportsbookServiceServer).GetBet(ctx, req.(*GetBetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SportsbookService_ListBets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SportsbookServiceServer).ListBets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SportsbookService_ListBets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SportsbookServiceServer).ListBets(ctx, req.(*ListBetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SportsbookService_SettleBet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SettleBetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SportsbookServiceServer).SettleBet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SportsbookService_SettleBet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SportsbookServiceServer).SettleBet(ctx, req.(*SettleBetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SportsbookService_ServiceDesc is the grpc.ServiceDesc for SportsbookService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SportsbookService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sportsbook.SportsbookService",
	HandlerType: (*SportsbookServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PlaceBet",
			Handler:    _SportsbookService_PlaceBet_Handler,
		},
		{
			MethodName: "GetBet",
			Handler:    _SportsbookService_GetBet_Handler,
		},
		{
			MethodName: "ListBets",
			Handler:    _SportsbookService_ListBets_Handler,
		},
		{
			MethodName: "SettleBet",
			Handler:    _SportsbookService_SettleBet_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/proto/sportsbook.proto",
}
