// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: internal/proto/wallet.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Currency      string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceRequest) Reset() {
	*x = GetBalanceRequest{}
	mi := &file_internal_proto_wallet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceRequest) ProtoMessage() {}

func (x *GetBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_wallet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceRequest.ProtoReflect.Descriptor instead.
func (*GetBalanceRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_wallet_proto_rawDescGZIP(), []int{0}
}

func (x *GetBalanceRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetBalanceRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type GetBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Currency      string                 `protobuf:"bytes,1,opt,name=currency,proto3" json:"currency,omitempty"`
	Balance       string                 `protobuf:"bytes,2,opt,name=balance,proto3" json:"balance,omitempty"`
	FiatCurrency  string                 `protobuf:"bytes,3,opt,name=fiat_currency,json=fiatCurrency,proto3" json:"fiat_currency,omitempty"`
	FiatValue     string                 `protobuf:"bytes,4,opt,name=fiat_value,json=fiatValue,proto3" json:"fiat_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceResponse) Reset() {
	*x = GetBalanceResponse{}
	mi := &file_internal_proto_wallet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceResponse) ProtoMessage() {}

func (x *GetBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_wallet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceResponse.ProtoReflect.Descriptor instead.
func (*GetBalanceResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_wallet_proto_rawDescGZIP(), []int{1}
}

func (x *GetBalanceResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *GetBalanceResponse) GetBalance() string {
	if x != nil {
		return x.Balance
	}
	return ""
}

func (x *GetBalanceResponse) GetFiatCurrency() string {
	if x != nil {
		return x.FiatCurrency
	}
	return ""
}

func (x *GetBalanceResponse) GetFiatValue() string {
	if x != nil {
		return x.FiatValue
	}
	return ""
}

type Transaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	WalletId      string                 `protobuf:"bytes,3,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Amount        string                 `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount,omitempty"`
	BalanceBefore string                 `protobuf:"bytes,6,opt,name=balance_before,json=balanceBefore,proto3" json:"balance_before,omitempty"`
	BalanceAfter  string                 `protobuf:"bytes,7,opt,name=balance_after,json=balanceAfter,proto3" json:"balance_after,omitempty"`
	Status        string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	ReferenceId   string                 `protobuf:"bytes,9,opt,name=reference_id,json=referenceId,proto3" json:"reference_id,omitempty"`
	Metadata      string                 `protobuf:"bytes,10,opt,name=metadata,proto3" json:"metadata,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	FiatValue     string                 `protobuf:"bytes,12,opt,name=fiat_value,json=fiatValue,proto3" json:"fiat_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_internal_proto_wallet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_wallet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_internal_proto_wallet_proto_rawDescGZIP(), []int{2}
}

func (x *Transaction) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Transaction) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Transaction) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

func (x *Transaction) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Transaction) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *Transaction) GetBalanceBefore() string {
	if x != nil {
		return x.BalanceBefore
	}
	return ""
}

func (x *Transaction) GetBalanceAfter() string {
	if x != nil {
		return x.BalanceAfter
	}
	return ""
}

func (x *Transaction) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Transaction) GetReferenceId() string {
	if x != nil {
		return x.ReferenceId
	}
	return ""
}

func (x *Transaction) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

func (x *Transaction) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Transaction) GetFiatValue() string {
	if x != nil {
		return x.FiatValue
	}
	return ""
}

type ListTransactionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTransactionsRequest) Reset() {
	*x = ListTransactionsRequest{}
	mi := &file_internal_proto_wallet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTransactionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTransactionsRequest) ProtoMessage() {}

func (x *ListTransactionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_wallet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTransactionsRequest.ProtoReflect.Descriptor instead.
func (*ListTransactionsRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_wallet_proto_rawDescGZIP(), []int{3}
}

func (x *ListTransactionsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListTransactionsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListTransactionsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListTransactionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []*Transaction         `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTransactionsResponse) Reset() {
	*x = ListTransactionsResponse{}
	mi := &file_internal_proto_wallet_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTransactionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTransactionsResponse) ProtoMessage() {}

func (x *ListTransactionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_wallet_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTransactionsResponse.ProtoReflect.Descriptor instead.
func (*ListTransactionsResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_wallet_proto_rawDescGZIP(), []int{4}
}

func (x *ListTransactionsResponse) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

type GetRatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRatesRequest) Reset() {
	*x = GetRatesRequest{}
	mi := &file_internal_proto_wallet_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRatesRequest) ProtoMessage() {}

func (x *GetRatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_wallet_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRatesRequest.ProtoReflect.Descriptor instead.
func (*GetRatesRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_wallet_proto_rawDescGZIP(), []int{5}
}

type GetRatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FiatCurrency  string                 `protobuf:"bytes,1,opt,name=fiat_currency,json=fiatCurrency,proto3" json:"fiat_currency,omitempty"`
	Rates         map[string]string      `protobuf:"bytes,2,rep,name=rates,proto3" json:"rates,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRatesResponse) Reset() {
	*x = GetRatesResponse{}
	mi := &file_internal_proto_wallet_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRatesResponse) ProtoMessage() {}

func (x *GetRatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_wallet_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRatesResponse.ProtoReflect.Descriptor instead.
func (*GetRatesResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_wallet_proto_rawDescGZIP(), []int{6}
}

func (x *GetRatesResponse) GetFiatCurrency() string {
	if x != nil {
		return x.FiatCurrency
	}
	return ""
}

func (x *GetRatesResponse) GetRates() map[string]string {
	if x != nil {
		return x.Rates
	}
	return nil
}

type GetDepositAddressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Currency      string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	Chain         string                 `protobuf:"bytes,3,opt,name=chain,proto3" json:"chain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDepositAddressRequest) Reset() {
	*x = GetDepositAddressRequest{}
	mi := &file_internal_proto_wallet_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDepositAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDepositAddressRequest) ProtoMessage() {}

func (x *GetDepositAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_wallet_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDepositAddressRequest.ProtoReflect.Descriptor instead.
func (*GetDepositAddressRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_wallet_proto_rawDescGZIP(), []int{7}
}

func (x *GetDepositAddressRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetDepositAddressRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *GetDepositAddressRequest) GetChain() string {
	if x != nil {
		return x.Chain
	}
	return ""
}

type GetDepositAddressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Chain         string                 `protobuf:"bytes,2,opt,name=chain,proto3" json:"chain,omitempty"`
	Currency      string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDepositAddressResponse) Reset() {
	*x = GetDepositAddressResponse{}
	mi := &file_internal_proto_wallet_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDepositAddressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDepositAddressResponse) ProtoMessage() {}

func (x *GetDepositAddressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_wallet_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDepositAddressResponse.ProtoReflect.Descriptor instead.
func (*GetDepositAddressResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_wallet_proto_rawDescGZIP(), []int{8}
}

func (x *GetDepositAddressResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *GetDepositAddressResponse) GetChain() string {
	if x != nil {
		return x.Chain
	}
	return ""
}

func (x *GetDepositAddressResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type RequestWithdrawalRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	UserId             string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Currency           string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	Amount             string                 `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	DestinationAddress string                 `protobuf:"bytes,4,opt,name=destination_address,json=destinationAddress,proto3" json:"destination_address,omitempty"`
	Chain              string                 `protobuf:"bytes,5,opt,name=chain,proto3" json:"chain,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RequestWithdrawalRequest) Reset() {
	*x = RequestWithdrawalRequest{}
	mi := &file_internal_proto_wallet_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestWithdrawalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestWithdrawalRequest) ProtoMessage() {}

func (x *RequestWithdrawalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_wallet_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestWithdrawalRequest.ProtoReflect.Descriptor instead.
func (*RequestWithdrawalRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_wallet_proto_rawDescGZIP(), []int{9}
}

func (x *RequestWithdrawalRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RequestWithdrawalRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *RequestWithdrawalRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *RequestWithdrawalRequest) GetDestinationAddress() string {
	if x != nil {
		return x.DestinationAddress
	}
	return ""
}

func (x *RequestWithdrawalRequest) GetChain() string {
	if x != nil {
		return x.Chain
	}
	return ""
}

type RequestWithdrawalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WithdrawalId  string                 `protobuf:"bytes,1,opt,name=withdrawal_id,json=withdrawalId,proto3" json:"withdrawal_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestWithdrawalResponse) Reset() {
	*x = RequestWithdrawalResponse{}
	mi := &file_internal_proto_wallet_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestWithdrawalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestWithdrawalResponse) ProtoMessage() {}

func (x *RequestWithdrawalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_wallet_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestWithdrawalResponse.ProtoReflect.Descriptor instead.
func (*RequestWithdrawalResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_wallet_proto_rawDescGZIP(), []int{10}
}

func (x *RequestWithdrawalResponse) GetWithdrawalId() string {
	if x != nil {
		return x.WithdrawalId
	}
	return ""
}

func (x *RequestWithdrawalResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ProcessDepositWebhookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Body          string                 `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessDepositWebhookRequest) Reset() {
	*x = ProcessDepositWebhookRequest{}
	mi := &file_internal_proto_wallet_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessDepositWebhookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessDepositWebhookRequest) ProtoMessage() {}

func (x *ProcessDepositWebhookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_wallet_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessDepositWebhookRequest.ProtoReflect.Descriptor instead.
func (*ProcessDepositWebhookRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_wallet_proto_rawDescGZIP(), []int{11}
}

func (x *ProcessDepositWebhookRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *ProcessDepositWebhookRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

type ProcessDepositWebhookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResponseBody  string                 `protobuf:"bytes,1,opt,name=response_body,json=responseBody,proto3" json:"response_body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessDepositWebhookResponse) Reset() {
	*x = ProcessDepositWebhookResponse{}
	mi := &file_internal_proto_wallet_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessDepositWebhookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessDepositWebhookResponse) ProtoMessage() {}

func (x *ProcessDepositWebhookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_wallet_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessDepositWebhookResponse.ProtoReflect.Descriptor instead.
func (*ProcessDepositWebhookResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_wallet_proto_rawDescGZIP(), []int{12}
}

func (x *ProcessDepositWebhookResponse) GetResponseBody() string {
	if x != nil {
		return x.ResponseBody
	}
	return ""
}

type WithdrawalRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId             string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Currency           string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	Amount             string                 `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	DestinationAddress string                 `protobuf:"bytes,5,opt,name=destination_address,json=destinationAddress,proto3" json:"destination_address,omitempty"`
	Chain              string                 `protobuf:"bytes,6,opt,name=chain,proto3" json:"chain,omitempty"`
	Status             string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	TxHash             string                 `protobuf:"bytes,8,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	CreatedAt          string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *WithdrawalRequest) Reset() {
	*x = WithdrawalRequest{}
	mi := &file_internal_proto_wallet_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WithdrawalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawalRequest) ProtoMessage() {}

func (x *WithdrawalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_wallet_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawalRequest.ProtoReflect.Descriptor instead.
func (*WithdrawalRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_wallet_proto_rawDescGZIP(), []int{13}
}

func (x *WithdrawalRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WithdrawalRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *WithdrawalRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *WithdrawalRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *WithdrawalRequest) GetDestinationAddress() string {
	if x != nil {
		return x.DestinationAddress
	}
	return ""
}

func (x *WithdrawalRequest) GetChain() string {
	if x != nil {
		return x.Chain
	}
	return ""
}

func (x *WithdrawalRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *WithdrawalRequest) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *WithdrawalRequest) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type ListPendingWithdrawalsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPendingWithdrawalsRequest) Reset() {
	*x = ListPendingWithdrawalsRequest{}
	mi := &file_internal_proto_wallet_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPendingWithdrawalsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPendingWithdrawalsRequest) ProtoMessage() {}

func (x *ListPendingWithdrawalsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_wallet_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPendingWithdrawalsRequest.ProtoReflect.Descriptor instead.
func (*ListPendingWithdrawalsRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_wallet_proto_rawDescGZIP(), []int{14}
}

func (x *ListPendingWithdrawalsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListPendingWithdrawalsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListPendingWithdrawalsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Withdrawals   []*WithdrawalRequest   `protobuf:"bytes,1,rep,name=withdrawals,proto3" json:"withdrawals,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPendingWithdrawalsResponse) Reset() {
	*x = ListPendingWithdrawalsResponse{}
	mi := &file_internal_proto_wallet_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPendingWithdrawalsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPendingWithdrawalsResponse) ProtoMessage() {}

func (x *ListPendingWithdrawalsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_wallet_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPendingWithdrawalsResponse.ProtoReflect.Descriptor instead.
func (*ListPendingWithdrawalsResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_wallet_proto_rawDescGZIP(), []int{15}
}

func (x *ListPendingWithdrawalsResponse) GetWithdrawals() []*WithdrawalRequest {
	if x != nil {
		return x.Withdrawals
	}
	return nil
}

type ReviewWithdrawalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WithdrawalId  string                 `protobuf:"bytes,1,opt,name=withdrawal_id,json=withdrawalId,proto3" json:"withdrawal_id,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	TxHash        string                 `protobuf:"bytes,3,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	ReviewedBy    string                 `protobuf:"bytes,4,opt,name=reviewed_by,json=reviewedBy,proto3" json:"reviewed_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReviewWithdrawalRequest) Reset() {
	*x = ReviewWithdrawalRequest{}
	mi := &file_internal_proto_wallet_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewWithdrawalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewWithdrawalRequest) ProtoMessage() {}

func (x *ReviewWithdrawalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_wallet_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewWithdrawalRequest.ProtoReflect.Descriptor instead.
func (*ReviewWithdrawalRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_wallet_proto_rawDescGZIP(), []int{16}
}

func (x *ReviewWithdrawalRequest) GetWithdrawalId() string {
	if x != nil {
		return x.WithdrawalId
	}
	return ""
}

func (x *ReviewWithdrawalRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ReviewWithdrawalRequest) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *ReviewWithdrawalRequest) GetReviewedBy() string {
	if x != nil {
		return x.ReviewedBy
	}
	return ""
}

type ReviewWithdrawalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReviewWithdrawalResponse) Reset() {
	*x = ReviewWithdrawalResponse{}
	mi := &file_internal_proto_wallet_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewWithdrawalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewWithdrawalResponse) ProtoMessage() {}

func (x *ReviewWithdrawalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_wallet_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewWithdrawalResponse.ProtoReflect.Descriptor instead.
func (*ReviewWithdrawalResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_wallet_proto_rawDescGZIP(), []int{17}
}

func (x *ReviewWithdrawalResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_internal_proto_wallet_proto protoreflect.FileDescriptor

const file_internal_proto_wallet_proto_rawDesc = "" +
	"\n" +
	"\x1binternal/proto/wallet.proto\x12\x06wallet\"H\n" +
	"\x11GetBalanceRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\"\x8e\x01\n" +
	"\x12GetBalanceResponse\x12\x1a\n" +
	"\bcurrency\x18\x01 \x01(\tR\bcurrency\x12\x18\n" +
	"\abalance\x18\x02 \x01(\tR\abalance\x12#\n" +
	"\rfiat_currency\x18\x03 \x01(\tR\ffiatCurrency\x12\x1d\n" +
	"\n" +
	"fiat_value\x18\x04 \x01(\tR\tfiatValue\"\xe0\x02\n" +
	"\vTransaction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\twallet_id\x18\x03 \x01(\tR\bwalletId\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\tR\x06amount\x12%\n" +
	"\x0ebalance_before\x18\x06 \x01(\tR\rbalanceBefore\x12#\n" +
	"\rbalance_after\x18\a \x01(\tR\fbalanceAfter\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12!\n" +
	"\freference_id\x18\t \x01(\tR\vreferenceId\x12\x1a\n" +
	"\bmetadata\x18\n" +
	" \x01(\tR\bmetadata\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"fiat_value\x18\f \x01(\tR\tfiatValue\"c\n" +
	"\x17ListTransactionsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"S\n" +
	"\x18ListTransactionsResponse\x127\n" +
	"\ftransactions\x18\x01 \x03(\v2\x13.wallet.TransactionR\ftransactions\"\x11\n" +
	"\x0fGetRatesRequest\"\xac\x01\n" +
	"\x10GetRatesResponse\x12#\n" +
	"\rfiat_currency\x18\x01 \x01(\tR\ffiatCurrency\x129\n" +
	"\x05rates\x18\x02 \x03(\v2#.wallet.GetRatesResponse.RatesEntryR\x05rates\x1a8\n" +
	"\n" +
	"RatesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"e\n" +
	"\x18GetDepositAddressRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\x12\x14\n" +
	"\x05chain\x18\x03 \x01(\tR\x05chain\"g\n" +
	"\x19GetDepositAddressResponse\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x14\n" +
	"\x05chain\x18\x02 \x01(\tR\x05chain\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\"\xae\x01\n" +
	"\x18RequestWithdrawalRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\tR\x06amount\x12/\n" +
	"\x13destination_address\x18\x04 \x01(\tR\x12destinationAddress\x12\x14\n" +
	"\x05chain\x18\x05 \x01(\tR\x05chain\"X\n" +
	"\x19RequestWithdrawalResponse\x12#\n" +
	"\rwithdrawal_id\x18\x01 \x01(\tR\fwithdrawalId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"\xbb\x01\n" +
	"\x1cProcessDepositWebhookRequest\x12\x12\n" +
	"\x04body\x18\x01 \x01(\tR\x04body\x12K\n" +
	"\aheaders\x18\x02 \x03(\v21.wallet.ProcessDepositWebhookRequest.HeadersEntryR\aheaders\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"D\n" +
	"\x1dProcessDepositWebhookResponse\x12#\n" +
	"\rresponse_body\x18\x01 \x01(\tR\fresponseBody\"\x87\x02\n" +
	"\x11WithdrawalRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\tR\x06amount\x12/\n" +
	"\x13destination_address\x18\x05 \x01(\tR\x12destinationAddress\x12\x14\n" +
	"\x05chain\x18\x06 \x01(\tR\x05chain\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12\x17\n" +
	"\atx_hash\x18\b \x01(\tR\x06txHash\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\"P\n" +
	"\x1dListPendingWithdrawalsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"]\n" +
	"\x1eListPendingWithdrawalsResponse\x12;\n" +
	"\vwithdrawals\x18\x01 \x03(\v2\x19.wallet.WithdrawalRequestR\vwithdrawals\"\x90\x01\n" +
	"\x17ReviewWithdrawalRequest\x12#\n" +
	"\rwithdrawal_id\x18\x01 \x01(\tR\fwithdrawalId\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12\x17\n" +
	"\atx_hash\x18\x03 \x01(\tR\x06txHash\x12\x1f\n" +
	"\vreviewed_by\x18\x04 \x01(\tR\n" +
	"reviewedBy\"2\n" +
	"\x18ReviewWithdrawalResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2\xc4\x05\n" +
	"\rWalletService\x12=\n" +
	"\bGetRates\x12\x17.wallet.GetRatesRequest\x1a\x18.wallet.GetRatesResponse\x12C\n" +
	"\n" +
	"GetBalance\x12\x19.wallet.GetBalanceRequest\x1a\x1a.wallet.GetBalanceResponse\x12U\n" +
	"\x10ListTransactions\x12\x1f.wallet.ListTransactionsRequest\x1a .wallet.ListTransactionsResponse\x12X\n" +
	"\x11GetDepositAddress\x12 .wallet.GetDepositAddressRequest\x1a!.wallet.GetDepositAddressResponse\x12X\n" +
	"\x11RequestWithdrawal\x12 .wallet.RequestWithdrawalRequest\x1a!.wallet.RequestWithdrawalResponse\x12d\n" +
	"\x15ProcessDepositWebhook\x12$.wallet.ProcessDepositWebhookRequest\x1a%.wallet.ProcessDepositWebhookResponse\x12g\n" +
	"\x16ListPendingWithdrawals\x12%.wallet.ListPendingWithdrawalsRequest\x1a&.wallet.ListPendingWithdrawalsResponse\x12U\n" +
	"\x10ReviewWithdrawal\x12\x1f.wallet.ReviewWithdrawalRequest\x1a .wallet.ReviewWithdrawalResponseB8Z6github.com/realyoussefhossam/betmonster/internal/protob\x06proto3"

var (
	file_internal_proto_wallet_proto_rawDescOnce sync.Once
	file_internal_proto_wallet_proto_rawDescData []byte
)

func file_internal_proto_wallet_proto_rawDescGZIP() []byte {
	file_internal_proto_wallet_proto_rawDescOnce.Do(func() {
		file_internal_proto_wallet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_wallet_proto_rawDesc), len(file_internal_proto_wallet_proto_rawDesc)))
	})
	return file_internal_proto_wallet_proto_rawDescData
}

var file_internal_proto_wallet_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_internal_proto_wallet_proto_goTypes = []any{
	(*GetBalanceRequest)(nil),              // 0: wallet.GetBalanceRequest
	(*GetBalanceResponse)(nil),             // 1: wallet.GetBalanceResponse
	(*Transaction)(nil),                    // 2: wallet.Transaction
	(*ListTransactionsRequest)(nil),        // 3: wallet.ListTransactionsRequest
	(*ListTransactionsResponse)(nil),       // 4: wallet.ListTransactionsResponse
	(*GetRatesRequest)(nil),                // 5: wallet.GetRatesRequest
	(*GetRatesResponse)(nil),               // 6: wallet.GetRatesResponse
	(*GetDepositAddressRequest)(nil),       // 7: wallet.GetDepositAddressRequest
	(*GetDepositAddressResponse)(nil),      // 8: wallet.GetDepositAddressResponse
	(*RequestWithdrawalRequest)(nil),       // 9: wallet.RequestWithdrawalRequest
	(*RequestWithdrawalResponse)(nil),      // 10: wallet.RequestWithdrawalResponse
	(*ProcessDepositWebhookRequest)(nil),   // 11: wallet.ProcessDepositWebhookRequest
	(*ProcessDepositWebhookResponse)(nil),  // 12: wallet.ProcessDepositWebhookResponse
	(*WithdrawalRequest)(nil),              // 13: wallet.WithdrawalRequest
	(*ListPendingWithdrawalsRequest)(nil),  // 14: wallet.ListPendingWithdrawalsRequest
	(*ListPendingWithdrawalsResponse)(nil), // 15: wallet.ListPendingWithdrawalsResponse
	(*ReviewWithdrawalRequest)(nil),        // 16: wallet.ReviewWithdrawalRequest
	(*ReviewWithdrawalResponse)(nil),       // 17: wallet.ReviewWithdrawalResponse
	nil,                                    // 18: wallet.GetRatesResponse.RatesEntry
	nil,                                    // 19: wallet.ProcessDepositWebhookRequest.HeadersEntry
}
var file_internal_proto_wallet_proto_depIdxs = []int32{
	2,  // 0: wallet.ListTransactionsResponse.transactions:type_name -> wallet.Transaction
	18, // 1: wallet.GetRatesResponse.rates:type_name -> wallet.GetRatesResponse.RatesEntry
	19, // 2: wallet.ProcessDepositWebhookRequest.headers:type_name -> wallet.ProcessDepositWebhookRequest.HeadersEntry
	13, // 3: wallet.ListPendingWithdrawalsResponse.withdrawals:type_name -> wallet.WithdrawalRequest
	5,  // 4: wallet.WalletService.GetRates:input_type -> wallet.GetRatesRequest
	0,  // 5: wallet.WalletService.GetBalance:input_type -> wallet.GetBalanceRequest
	3,  // 6: wallet.WalletService.ListTransactions:input_type -> wallet.ListTransactionsRequest
	7,  // 7: wallet.WalletService.GetDepositAddress:input_type -> wallet.GetDepositAddressRequest
	9,  // 8: wallet.WalletService.RequestWithdrawal:input_type -> wallet.RequestWithdrawalRequest
	11, // 9: wallet.WalletService.ProcessDepositWebhook:input_type -> wallet.ProcessDepositWebhookRequest
	14, // 10: wallet.WalletService.ListPendingWithdrawals:input_type -> wallet.ListPendingWithdrawalsRequest
	16, // 11: wallet.WalletService.ReviewWithdrawal:input_type -> wallet.ReviewWithdrawalRequest
	6,  // 12: wallet.WalletService.GetRates:output_type -> wallet.GetRatesResponse
	1,  // 13: wallet.WalletService.GetBalance:output_type -> wallet.GetBalanceResponse
	4,  // 14: wallet.WalletService.ListTransactions:output_type -> wallet.ListTransactionsResponse
	8,  // 15: wallet.WalletService.GetDepositAddress:output_type -> wallet.GetDepositAddressResponse
	10, // 16: wallet.WalletService.RequestWithdrawal:output_type -> wallet.RequestWithdrawalResponse
	12, // 17: wallet.WalletService.ProcessDepositWebhook:output_type -> wallet.ProcessDepositWebhookResponse
	15, // 18: wallet.WalletService.ListPendingWithdrawals:output_type -> wallet.ListPendingWithdrawalsResponse
	17, // 19: wallet.WalletService.ReviewWithdrawal:output_type -> wallet.ReviewWithdrawalResponse
	12, // [12:20] is the sub-list for method output_type
	4,  // [4:12] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_internal_proto_wallet_proto_init() }
func file_internal_proto_wallet_proto_init() {
	if File_internal_proto_wallet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_wallet_proto_rawDesc), len(file_internal_proto_wallet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_wallet_proto_goTypes,
		DependencyIndexes: file_internal_proto_wallet_proto_depIdxs,
		MessageInfos:      file_internal_proto_wallet_proto_msgTypes,
	}.Build()
	File_internal_proto_wallet_proto = out.File
	file_internal_proto_wallet_proto_goTypes = nil
	file_internal_proto_wallet_proto_depIdxs = nil
}
