FROM golang:1.26-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 go build -o bin/oddsfeed-service ./cmd/oddsfeed

FROM alpine:3.21

RUN apk add --no-cache ca-certificates

WORKDIR /app
COPY --from=builder /app/bin/oddsfeed-service ./oddsfeed-service
COPY --from=builder /app/internal/oddsfeed/migrations ./internal/oddsfeed/migrations

EXPOSE 8082 50052
ENTRYPOINT ["./oddsfeed-service"]
