FROM golang:1.26-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 go build -o bin/wallet ./cmd/wallet

FROM alpine:3.21

RUN apk add --no-cache ca-certificates

WORKDIR /app
COPY --from=builder /app/bin/wallet ./wallet
COPY --from=builder /app/wallet/migrations ./wallet/migrations

EXPOSE 8081 50051
ENTRYPOINT ["./wallet"]
