#!/usr/bin/env bash
set -euo pipefail

# Auto-configure a local xcash instance for BetMonster testing.
# Uses an anvil container as the local EVM chain and writes the resulting
# xcash appid/hmac_key back into BetMonster's .env.

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
XCASH_DIR="${ROOT}/deps/xcash"
XCASH_ENV="${XCASH_DIR}/.env"
BETMONSTER_ENV="${ROOT}/.env"
XCASH_CONTAINER="xcash_django"
ANVIL_CONTAINER="xcash_anvil"
XCASH_NETWORK="xcash_default"
XCASH_INTERNAL_URL="http://localhost:6688"

generate_secret() {
    LC_ALL=C tr -dc 'A-Za-z0-9' < /dev/urandom | head -c "$1"
}

mkdir -p "${ROOT}/deps"

# 1. Clone xcash if it does not already exist.
if [ ! -d "${XCASH_DIR}" ]; then
    echo "Cloning xcash into ${XCASH_DIR} ..."
    git clone https://github.com/xca-sh/xcash.git "${XCASH_DIR}"
fi

cd "${XCASH_DIR}"

# 2. Generate xcash environment file.
if [ ! -f "${XCASH_ENV}" ]; then
    echo "Initializing xcash .env ..."
    ./scripts/init_env.sh
fi

# 3. Append BetMonster-specific overrides (idempotent marker).
if ! grep -q "# BetMonster overrides" "${XCASH_ENV}" 2>/dev/null; then
    {
        echo ""
        echo "# BetMonster overrides"
        echo "SITE_DOMAIN=localhost"
        echo "LISTEN_TO=0.0.0.0"
        echo "ADMIN_PATH=admin"
        echo "WEBHOOK_ALLOW_INTERNAL_TARGETS=true"
        echo "SAAS_API_TOKEN=$(generate_secret 64)"
    } >> "${XCASH_ENV}"
    echo "Updated ${XCASH_ENV} with BetMonster overrides."
fi

# 4. Start the full xcash stack.
echo "Starting xcash stack ..."
docker compose up -d

# 5. Ensure an anvil container is running on the xcash network.
if docker ps -a --format '{{.Names}}' | grep -q "^${ANVIL_CONTAINER}$"; then
    echo "Recreating anvil container with correct entrypoint ..."
    docker rm -f "${ANVIL_CONTAINER}" >/dev/null 2>&1 || true
fi

echo "Starting anvil container on ${XCASH_NETWORK} ..."
docker run -d \
    --name "${ANVIL_CONTAINER}" \
    --network "${XCASH_NETWORK}" \
    --restart unless-stopped \
    -p 8545:8545 \
    --entrypoint anvil \
    ghcr.io/foundry-rs/foundry:v1.3.1 \
    --host 0.0.0.0 \
    --port 8545 \
    --chain-id 31337 \
    --block-time 12

# 6. Wait for the xcash web service to accept requests.
echo "Waiting for xcash at ${XCASH_INTERNAL_URL} ..."
for i in $(seq 1 60); do
    if curl -sS -o /dev/null -w '%{http_code}' "${XCASH_INTERNAL_URL}/admin/login/" 2>/dev/null | grep -qE '200|302'; then
        break
    fi
    if [ "$i" -eq 60 ]; then
        echo "Timed out waiting for xcash. Check logs with: docker logs ${XCASH_CONTAINER}"
        exit 1
    fi
    sleep 2
done

# 7. Run the bootstrap inside the xcash container.
echo "Bootstrapping anvil chain, contracts, wallet, and project ..."
BOOTSTRAP_SRC="${ROOT}/scripts/xcash_bootstrap.py"
XCASH_BOOTSTRAP="/tmp/xcash_bootstrap.py"
docker cp "${BOOTSTRAP_SRC}" "${XCASH_CONTAINER}:${XCASH_BOOTSTRAP}"
BOOTSTRAP_OUTPUT="$(docker exec "${XCASH_CONTAINER}" python "${XCASH_BOOTSTRAP}")"

if [ -z "${BOOTSTRAP_OUTPUT}" ]; then
    echo "Bootstrap produced no output."
    exit 1
fi

echo "${BOOTSTRAP_OUTPUT}"

# 8. Write xcash credentials into BetMonster .env.
APPID="$(echo "${BOOTSTRAP_OUTPUT}" | grep '^XCASH_APPID=' | cut -d '=' -f 2- || true)"
HMAC_KEY="$(echo "${BOOTSTRAP_OUTPUT}" | grep '^XCASH_HMAC_KEY=' | cut -d '=' -f 2- || true)"
WEBHOOK_SECRET="$(echo "${BOOTSTRAP_OUTPUT}" | grep '^XCASH_WEBHOOK_SECRET=' | cut -d '=' -f 2- || true)"

if [ -z "${APPID}" ] || [ -z "${HMAC_KEY}" ]; then
    echo "Could not extract xcash credentials from bootstrap output."
    exit 1
fi

if [ -f "${BETMONSTER_ENV}" ]; then
    # Remove old xcash lines to avoid duplicates.
    sed -i '/^XCASH_/d' "${BETMONSTER_ENV}" 2>/dev/null || true
fi

{
    echo ""
    echo "# xcash (auto-generated by scripts/setup-xcash.sh)"
    echo "XCASH_BASE_URL=${XCASH_INTERNAL_URL}"
    echo "XCASH_APPID=${APPID}"
    echo "XCASH_HMAC_KEY=${HMAC_KEY}"
    echo "XCASH_WEBHOOK_SECRET=${WEBHOOK_SECRET:-${HMAC_KEY}}"
} >> "${BETMONSTER_ENV}"

echo ""
echo "Local xcash configured for BetMonster. Credentials written to ${BETMONSTER_ENV}."
echo ""
echo "Note: the local xcash stack only activates the anvil chain with USDT, USDC, and ETH."
echo "Only anvil pairs will work for deposits here. Production chains (ethereum, bsc,"
echo "polygon, base, arbitrum-one, tron) must be configured separately in your real"
echo "xcash deployment before adding them to SUPPORTED_PAIRS in production."
